"""Alert rules, runbooks and drills stay consistent with each other (P4-09, ADR 0018).

ADR 0018 makes two things acceptance criteria rather than nice-to-haves: **every alert
names a runbook**, and **every alert can be deliberately triggered**. Both decay
silently — a metric gets renamed, a runbook is moved, an alert is added in a hurry — and
the failure only shows up when someone is paged at 3am with no next step. Hence tests.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import pytest
import yaml

from app import metrics
from app.api.http.metrics import PREFIX

ROOT = Path(__file__).parents[2]
ALERTS = ROOT / "deploy/prometheus/alerts.yml"
RUNBOOKS = ROOT / "docs/runbooks"
DRILLS = ROOT / "scripts/p4/drills"


def rules() -> list[dict[str, Any]]:
    document = yaml.safe_load(ALERTS.read_text(encoding="utf-8"))
    return [rule for group in document["groups"] for rule in group["rules"]]


def test_the_rule_file_parses_and_has_rules() -> None:
    assert len(rules()) >= 10


@pytest.mark.parametrize("rule", rules(), ids=lambda rule: str(rule.get("alert")))
def test_every_rule_has_a_severity_and_a_summary(rule: dict[str, Any]) -> None:
    assert rule.get("labels", {}).get("severity") in {"warning", "critical"}
    assert rule.get("annotations", {}).get("summary")


@pytest.mark.parametrize("rule", rules(), ids=lambda rule: str(rule.get("alert")))
def test_every_rule_points_at_a_runbook_that_exists(rule: dict[str, Any]) -> None:
    """A pager with no next step is the failure mode this prevents. A moved or renamed
    runbook is exactly how it happens."""
    runbook = rule["annotations"].get("runbook", "")
    assert runbook, f"{rule['alert']} names no runbook"
    # Some annotations point at a section (`…md §6`); the file is the part that must exist.
    path = ROOT / runbook.split(" ")[0]
    assert path.is_file(), f"{rule['alert']} names a missing runbook: {runbook}"


@pytest.mark.parametrize("rule", rules(), ids=lambda rule: str(rule.get("alert")))
def test_every_rule_only_references_metrics_this_service_exports(rule: dict[str, Any]) -> None:
    """An alert on a metric that does not exist never fires, and looks like coverage.

    This is the check that catches a rename: the series names live in `app/metrics.py`
    (plus the gauges the exporter computes), and an expression naming anything else is
    either a typo or a metric someone forgot to add.
    """
    exported = _exported_series()
    referenced = set(re.findall(rf"{PREFIX}(\w+)", rule["expr"]))
    unknown = sorted(
        name
        for name in referenced
        # Histogram suffixes are generated by the exposition, not declared.
        if _strip_suffix(name) not in exported
    )
    assert unknown == [], f"{rule['alert']} references unexported metric(s): {unknown}"


def _strip_suffix(name: str) -> str:
    for suffix in ("_bucket", "_sum", "_count"):
        if name.endswith(suffix):
            return name[: -len(suffix)]
    return name


def _exported_series() -> set[str]:
    """Every series name the scrape can contain: the registry's constants plus the
    gauges the exporter computes at scrape time."""
    from_registry = {
        value
        for name, value in vars(metrics).items()
        if name.isupper() and isinstance(value, str) and not name.startswith("_")
    }
    gauges = {
        "online_nodes",
        "active_daemon_connections",
        "active_terminal_connections",
        "running_sessions",
        "database_pool_usage",
        # V2-K1: both are computed in `_gauges` for the reason the registry's docstring
        # gives — a gauge is a question about the present.
        "knowledge_pending_jobs",
        "knowledge_dead_letter_age_seconds",
    }
    return from_registry | gauges


def test_every_runbook_referenced_by_an_alert_has_the_expected_shape() -> None:
    """A runbook without a diagnosis section is a title. The headings are what make it
    usable at 3am by someone who did not write it."""
    referenced = {rule["annotations"]["runbook"].split(" ")[0] for rule in rules()}
    for relative in sorted(referenced):
        text = (ROOT / relative).read_text(encoding="utf-8")
        lowered = text.lower()
        for required in ("alert", "symptom", "impact", "diagnos", "verify"):
            assert required in lowered, f"{relative} has no '{required}' section"
        # It must say what to actually run, not only describe the problem.
        assert "```" in text, f"{relative} contains no commands"


def test_every_alert_group_has_a_drill_script() -> None:
    """ADR 0018: an alert that has never been made to fire is one nobody knows how to
    handle. The drills are how that claim is kept true."""
    expected = {
        "heartbeat-loss.sh",
        "queue-saturation.sh",
        "timeout-surge.sh",
        "db-exhaustion.sh",
        "update-failure.sh",
    }
    present = {path.name for path in DRILLS.glob("*.sh")}
    assert expected <= present, f"missing drills: {sorted(expected - present)}"


def test_every_drill_is_executable_and_refuses_to_run_silently() -> None:
    """Several drills are disruptive. Each must confirm before acting, and say which
    metric and runbook it exercises — a drill that just breaks something teaches
    nothing."""
    import os

    for path in sorted(DRILLS.glob("*.sh")):
        if path.name.startswith("_"):
            continue
        assert os.access(path, os.X_OK), f"{path.name} is not executable"
        text = path.read_text(encoding="utf-8")
        assert "confirm " in text, f"{path.name} acts without confirmation"
        assert "follow_up " in text, f"{path.name} does not name its metric and runbook"


def test_the_six_runbooks_exist() -> None:
    """The set ADR 0018 requires. Named individually rather than counted, so adding a
    seventh does not accidentally satisfy a missing one."""
    for name in (
        "heartbeat-loss.md",
        "queue-saturation.md",
        "timeout-surge.md",
        "db-exhaustion.md",
        "update-failure.md",
        "backup-restore.md",
    ):
        assert (RUNBOOKS / name).is_file(), f"docs/runbooks/{name} is missing"


def test_no_runbook_contains_a_placeholder() -> None:
    """A runbook with a TODO in it is worse than none: it is trusted and then found
    empty at the moment it is needed."""
    for path in sorted(RUNBOOKS.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        for marker in ("TODO", "TBD", "FIXME", "XXX"):
            assert marker not in text, f"{path.name} contains {marker}"


def test_drill_harness_flags_exist() -> None:
    """Every flag a drill passes to a Python harness must be one the harness accepts.

    This exists because it caught a real break. `queue-saturation.sh` was written in P4-09,
    before the load harness existed, so its invocation was a guess (`--flood`, no base URL,
    no credentials). The harness landed in P4-11 with a different interface and nothing
    noticed until the drill was first run end to end — a drill that cannot start is
    indistinguishable from an alert that cannot fire.
    """
    import re

    for drill in sorted(DRILLS.glob("*.sh")):
        text = drill.read_text(encoding="utf-8")
        for harness_rel in set(re.findall(r"(scripts/p4/load/[a-z_]+\.py)", text)):
            harness = ROOT / harness_rel
            assert harness.exists(), f"{drill.name} references a missing harness {harness_rel}"
            accepted = set(
                re.findall(r'add_argument\("(--[a-z0-9-]+)"', harness.read_text("utf-8"))
            )
            for invocation in _harness_invocations(drill.read_text("utf-8")):
                used = set(re.findall(r"(?<![\w-])(--[a-z0-9-]+)", invocation))
                unknown = used - accepted - _WRAPPER_FLAGS
                assert not unknown, (
                    f"{drill.name} passes {sorted(unknown)} to {harness_rel}, "
                    f"which does not accept them"
                )


# Flags belonging to the wrapper (`uv run --project backend python ...`), not to the harness.
_WRAPPER_FLAGS = frozenset({"--project", "--with"})


def _harness_invocations(text: str) -> list[str]:
    """The actual command lines that run a harness, following backslash continuations.

    Scanning the whole file was the first attempt and it was wrong twice over: it matched
    a flag named inside an explanatory *comment* and it matched `--project`, which belongs
    to `uv run`. A check that reports flags nobody passes is worse than none, because the
    next person silences it.
    """
    invocations: list[str] = []
    lines = text.splitlines()
    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("#") or "$HARNESS" not in stripped:
            continue
        command = [stripped]
        cursor = index
        while command[-1].rstrip().endswith("\\") and cursor + 1 < len(lines):
            cursor += 1
            command.append(lines[cursor].strip())
        invocations.append(" ".join(part.rstrip("\\") for part in command))
    return invocations
