package tmux

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DefaultSocket keeps Cliora's sessions on a tmux server of their own (`-L`).
// Before PV-04 they shared the node owner's default server, which meant every
// option this file sets would have been set on *their* tmux too — and `mouse on`
// or `status off` arriving unannounced in a personal tmux is exactly the kind of
// change a node owner is entitled to refuse. A separate server also keeps
// `tmux ls` on the machine free of cliora-* noise.
//
// The cost is one-off and real: sessions on the old socket cannot be moved (tmux
// sessions belong to a server), so the upgrade that introduces this ends them.
// See LegacySessionNames and the privileged-node-posture runbook.
const DefaultSocket = "cliora"

// ConfigFileName is the generated tmux config. It is regenerated on every daemon
// start because history-limit follows session.scrollback_limit.
const ConfigFileName = "tmux.conf"

// confHeader explains the file to whoever opens it on the machine. Everything in
// here is load-bearing for a product behaviour, which is why none of it is
// configurable: making `mouse` an option would make "the terminal can scroll" an
// option too.
const confHeader = `# Generated by agentd — edits are overwritten on restart.
# Every option here backs a product behaviour; none of them is a preference.
#   mouse on         the browser terminal scrolls. tmux attaches using the
#                    alternate screen, where xterm.js has no scrollback of its
#                    own, and tmux disables mouse reporting by default — so
#                    without this the wheel is translated into arrow keys and
#                    scrolling up walks the shell's history instead.
#                    See plan/12/03 and ADR 0023.
#   history-limit    FR-TERM-004.AC-04 (at least 5000 lines). tmux's own default is
#                    2000, and the limit must be in place before a pane is created,
#                    which is why it lives in this file rather than a set-option.
#   escape-time 10   tmux's 500ms default makes Esc visibly laggy in the CLIs.
#   status off       the console draws its own chrome; a status line would eat a
#                    row and show information about tmux rather than the session.
`

// RenderConf returns the tmux configuration for a given scrollback limit.
func RenderConf(historyLimit int) string {
	var b strings.Builder
	b.WriteString(confHeader)
	b.WriteString("set -g mouse on\n")
	fmt.Fprintf(&b, "set -g history-limit %d\n", historyLimit)
	b.WriteString("set -sg escape-time 10\n")
	b.WriteString("set -g status off\n")
	// xterm.js renders 24-bit colour; without declaring it tmux falls back to 256.
	fmt.Fprintf(&b, "set -g default-terminal %q\n", DefaultTerm)
	fmt.Fprintf(&b, "set -ga terminal-features \",%s:RGB\"\n", DefaultTerm)
	return b.String()
}

// ResolveConfigDir picks a stable, writable directory for the generated config.
// Stability matters more than location: the tmux server outlives the daemon, and a
// path that moved between runs would leave `-f` pointing at a file that is gone,
// which tmux answers by failing to start the server at all.
//
// systemd's RuntimeDirectory=agentd creates /run/agentd owned by the service user,
// which is how a non-root daemon gets a private, tmpfs-backed home for this. The
// other two branches cover rootless development and the e2e stack.
func ResolveConfigDir() string {
	if dir := os.Getenv("RUNTIME_DIRECTORY"); dir != "" {
		// systemd may pass a colon-separated list; the first entry is ours.
		if first, _, found := strings.Cut(dir, ":"); found {
			return first
		}
		return dir
	}
	if dir := os.Getenv("XDG_RUNTIME_DIR"); dir != "" {
		return filepath.Join(dir, "agentd")
	}
	return filepath.Join(os.TempDir(), fmt.Sprintf("agentd-%d", os.Getuid()))
}

// WriteConf renders the config into dir and returns its path. The write is atomic
// (temp file + rename) so a tmux server starting concurrently never reads half a
// file, and 0600 because this file decides how sessions on this machine behave.
func WriteConf(dir string, historyLimit int) (string, error) {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	path := filepath.Join(dir, ConfigFileName)
	tmp, err := os.CreateTemp(dir, ConfigFileName+".*")
	if err != nil {
		return "", err
	}
	defer func() { _ = os.Remove(tmp.Name()) }()
	if _, err := tmp.WriteString(RenderConf(historyLimit)); err != nil {
		_ = tmp.Close()
		return "", err
	}
	if err := tmp.Close(); err != nil {
		return "", err
	}
	if err := os.Chmod(tmp.Name(), 0o600); err != nil {
		return "", err
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		return "", err
	}
	return path, nil
}

// Prepare builds the production client: Cliora's own socket plus a freshly
// rendered config. A config that cannot be written is not fatal — a node that
// cannot scroll is still a working node — but the client then runs without `-f`
// and the caller is expected to say so in the log.
func Prepare(historyLimit int) (Client, error) {
	client := Client{Socket: DefaultSocket}
	path, err := WriteConf(ResolveConfigDir(), historyLimit)
	if err != nil {
		return client, err
	}
	client.ConfigPath = path
	return client, nil
}
