from __future__ import annotations

from collections import Counter
from pathlib import Path

from .model import DOC_ROOT, REPO_ROOT, TraceData, JsonObject, markdown_anchors
from .validate import coverage

GENERATED_NOTICE = "<!-- Generated by scripts/trace; do not edit directly. -->"


def _criterion_text(requirement: JsonObject, criterion: JsonObject) -> str:
    path = REPO_ROOT / requirement["source"]["path"]
    return markdown_anchors(path).get(criterion["source_anchor"], criterion["id"])


def _link_target(link: JsonObject) -> str:
    target = link["target"]
    return f"{target['kind']}:{target['locator']}"


def render_matrix(data: TraceData) -> str:
    by_source = data.links_by_source()
    lines = [
        "# Requirement traceability matrix",
        "",
        GENERATED_NOTICE,
        "",
        "| Requirement | Criterion | Source text | Plan/design | Implementation | Verification |",
        "|---|---|---|---|---|---|",
    ]
    for requirement in sorted(data.requirements, key=lambda item: item["id"]):
        for criterion in sorted(requirement["criteria"], key=lambda item: item["id"]):
            links = by_source.get(criterion["id"], [])
            plan = "<br>".join(
                _link_target(link)
                for link in links
                if link["type"] in {"planned_by", "specified_by", "refined_by"}
            )
            implementation = "<br>".join(
                _link_target(link) for link in links if link["type"] == "implemented_by"
            )
            verification = "<br>".join(
                _link_target(link)
                for link in links
                if link["type"]
                in {"verified_by", "measured_by", "validated_by", "guards_scope"}
            )
            source = (
                f"[{criterion['id']}]"
                f"(../../{requirement['source']['path']}#{criterion['source_anchor']})"
            )
            text = _criterion_text(requirement, criterion).replace("|", "\\|")
            lines.append(
                f"| {requirement['id']} | {source} | {text} | {plan or '—'} | "
                f"{implementation or '—'} | {verification or '—'} |"
            )
    lines.extend(["", "## Reverse index", ""])
    for link in sorted(
        data.links, key=lambda item: (item["target"]["locator"], item["from"])
    ):
        lines.append(f"- `{_link_target(link)}` ← `{link['from']}` ({link['type']})")
    return "\n".join(lines) + "\n"


def render_coverage(data: TraceData) -> str:
    result = coverage(data)
    lines = [
        "# Requirement coverage",
        "",
        GENERATED_NOTICE,
        "",
        f"- Criteria: **{result['summary']['total']}**",
        f"- Statically verifiable: **{result['summary']['verifiable']}**",
        f"- Absorbed into another criterion: **{result['summary']['covered_by_parent']}**",
        f"- Awaiting rewrite: **{result['summary']['needs_rewrite']}**",
        f"- Blocking static gaps: **{result['summary']['blocking']}**",
        "",
        "| Criterion | Kind | Classification | Status | Absorbed by | Missing | Modifier |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in result["criteria"]:
        lines.append(
            f"| {row['criterion_id']} | {row['kind']} | {row['classification']} | "
            f"{row['status']} | {row['covered_by'] or '—'} | "
            f"{', '.join(row['missing']) or '—'} | {row['modifier'] or '—'} |"
        )
    return "\n".join(lines) + "\n"


def render_gaps(data: TraceData) -> str:
    result = coverage(data)
    gaps = [row for row in result["criteria"] if row["missing"] or row["modifier"]]
    rewrites = [row for row in result["criteria"] if row["status"] == "needs-rewrite"]
    lines = ["# Traceability gaps", "", GENERATED_NOTICE, ""]
    lines.extend(["## Missing links", ""])
    if not gaps:
        lines.append("No static coverage gaps.")
    else:
        for row in gaps:
            lines.append(
                f"- **{row['criterion_id']}** ({row['criticality']}): "
                f"missing {', '.join(row['missing']) or 'none'}"
                f"{'; ' + row['modifier'] if row['modifier'] else ''}"
            )
    lines.extend(["", "## Awaiting requirement rewrite", ""])
    if not rewrites:
        lines.append("No criterion is queued for rewrite.")
    else:
        lines.append(
            "These are not link gaps. The PRD text itself cannot be decided as written, "
            "so no test may claim them."
        )
        lines.append("")
        for row in rewrites:
            lines.append(f"- **{row['criterion_id']}** ({row['criticality']})")
    return "\n".join(lines) + "\n"


def render_mvp(data: TraceData) -> str:
    result = coverage(data, "mvp")
    lines = [
        "# MVP and security release view",
        "",
        GENERATED_NOTICE,
        "",
        "> This committed view is static. A release verdict requires a same-commit "
        "`trace-snapshot.json`.",
        "",
        "| Criterion | Type | Static status | Missing |",
        "|---|---|---|---|",
    ]
    for row in result["criteria"]:
        lines.append(
            f"| {row['criterion_id']} | {row['kind']} | {row['status']} | "
            f"{', '.join(row['missing']) or '—'} |"
        )
    return "\n".join(lines) + "\n"


def render_owners(data: TraceData) -> str:
    counts = Counter(item["owner"] for item in data.requirements)
    lines = [
        "# Requirement owners",
        "",
        GENERATED_NOTICE,
        "",
        "| Owner | Requirements | IDs |",
        "|---|---:|---|",
    ]
    for owner in sorted(counts):
        ids = ", ".join(
            item["id"] for item in data.requirements if item["owner"] == owner
        )
        lines.append(f"| {owner} | {counts[owner]} | {ids} |")
    return "\n".join(lines) + "\n"


def render_historical_gaps() -> str:
    return """# Historical traceability gaps

<!-- Generated by scripts/trace; do not edit directly. -->

| Phase | Recorded verdict | Evidence classification | Remaining qualification |
|---|---|---|---|
| P0 | No-Go | historical claim + local executed evidence | Recovery blocker was closed by P2; the P0 snapshot remains No-Go |
| P1 | Conditional / formal No-Go | historical claim + local results | CI, WebKit, and six-platform install matrix were not observed in that report |
| P2 | Conditional Go | historical claim + local results | `.github/workflows/p2.yml` still required a real runner |
| P3 | Conditional Go | local evidence pack | `.github/workflows/p3.yml` real-runner/WebKit leg was outstanding |
| P4 | Go subject to conditions | local/CI-shaped evidence and explicit skips | Release-branch workflow, production secrets, backup, and deployed edge remain conditions |

The former references to `research/01/06-requirement-traceability.md` section 10 were
inconsistent: that document ended at section 9. Current per-requirement views are generated in
this directory; historical prose is not promoted to observed same-commit evidence.
"""


def rendered_documents(data: TraceData) -> dict[Path, str]:
    return {
        DOC_ROOT / "matrix.md": render_matrix(data),
        DOC_ROOT / "coverage.md": render_coverage(data),
        DOC_ROOT / "gaps.md": render_gaps(data),
        DOC_ROOT / "mvp.md": render_mvp(data),
        DOC_ROOT / "owners.md": render_owners(data),
        DOC_ROOT / "historical-gaps.md": render_historical_gaps(),
    }


def render(data: TraceData, *, check: bool) -> list[str]:
    drift: list[str] = []
    DOC_ROOT.mkdir(parents=True, exist_ok=True)
    for path, content in rendered_documents(data).items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                drift.append(path.relative_to(REPO_ROOT).as_posix())
        else:
            path.write_text(content, encoding="utf-8")
    return drift
